### ISSUE TITLE
Extension for Text/HTML

### ISSUE THREAD

**Issue by dlfivefifty** [shashi/Reel.jl#3]
I get the error

LoadError: MethodError: `extension` has no method matching extension(::MIME{symbol("text/html")})
while loading In[3], in expression starting on line 1

 in push! at /Users/solver/.julia/v0.4/Reel/src/Reel.jl:40
 in roll at /Users/solver/.julia/v0.4/Reel/src/Reel.jl:93

**Comment by shashi** [comment]
Looks like what you need is Cairo.jl. Installing that should magically fix things.

I know it's not the most ideal error message for this thing. Will fix this.

**Comment by dlfivefifty** [comment]
No, I have Cairo and it doesn’t help…

**Comment by shashi** [comment]
okay what i said is only correct in context of compose/gadfly.

The thing you are trying to render needs to have writemime type defined for either PNG / JPEG mime types.

**Comment by dlfivefifty** [comment]
I got the error running

film = roll(fps=30, duration=2) do t, dt
    plot([x -> sin(x+t*π), x -> cos(x+t*π)], 0, 6)
end

in the latest Jupyter.  Here’s my versioninfo():

Julia Version 0.4.0-rc1
Commit e5c6964 (2015-09-09 16:07 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by dlfivefifty** [comment]
Jupyter isn’t relevant, I get the same message on the command line:

julia> using Cairo,Gadfly,Reel

julia> film = roll(fps=30, duration=2) do t, dt
           plot([x -> sin(x+t*π), x -> cos(x+t*π)], 0, 6)
       end
ERROR: MethodError: `extension` has no method matching extension(::MIME{symbol("text/html")})
 in push! at /Users/solver/.julia/v0.4/Reel/src/Reel.jl:40
 in roll at /Users/solver/.julia/v0.4/Reel/src/Reel.jl:93

**Comment by shashi** [comment]
Weird. @dlfivefifty just tried it in 0.4, it works...

**Comment by tawheeler** [comment]
Stale and looks like it is solved. Will close in a few days if noone objects.

**Comment by RuohanZhan** [comment]
I have the same problem here, the  version info is:
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)

**Comment by irving-school-of-ai** [comment]
It's not solved.  I have the same issue:
julia> film = roll(fps=30, duration=2) do t, dt
           plot([x -> sin(x+t*pi), x -> cos(x+t*pi)], 0, 6)
       end
ERROR: MethodError: no method matching extension(::MIME{Symbol("text/html")})
Closest candidates are:
  extension(::String) at C:\Users\Barry Barrios\.julia\packages\Reel\sXEr9\src\Reel.jl:28
  extension(::MIME{Symbol("image/jpeg")}) at C:\Users\Barry Barrios\.julia\packages\Reel\sXEr9\src\Reel.jl:27
  extension(::MIME{Symbol("image/png")}) at C:\Users\Barry Barrios\.julia\packages\Reel\sXEr9\src\Reel.jl:26
Stacktrace:
 [1] push!(::Frames{MIME{Symbol("text/html")}}, ::Plot) at C:\Users\Barry Barrios\.julia\packages\Reel\sXEr9\src\Reel.jl:39
 [2] #roll#9(::Int64, ::Int64, ::Function, ::getfield(Main, Symbol("##21#24"))) at C:\Users\Barry Barrios\.julia\packages\Reel\sXEr9\src\Reel.jl:100
 [3] (::getfield(Reel, Symbol("#kw##roll")))(::NamedTuple{(:fps, :duration),Tuple{Int64,Int64}}, ::typeof(roll), ::Function) at .\none:0
 [4] top-level scope at none:0

**Comment by MaximeBouton** [comment]
@irving-school-of-ai could you confirm that it fixed the problem before we close the issue?
